import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {  useEffect } from 'react';

const Home: NextPage = () => {

  const handleScroll = () => {
    const topDistance = window.pageYOffset;
    const layers = document.querySelectorAll<HTMLElement>("[data-type='parallax']");
    layers.forEach(layer => {
      if(topDistance < 700){
        const depth = layer.getAttribute('data-depth');
        const movement = -(topDistance * parseFloat(depth??"0"));
        const translate3d = 'translate3d(0, ' + movement + 'px, 0)';
        layer.style.transform = translate3d;
      }else{

      }
    });

  }

  useEffect(() => { 
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
});
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto"/>
      </Head>
      <div className="container">
      <div className="nigelParalax" data-type='parallax' data-depth="0.10">
          <div data-type='parallax' data-depth="0.20" className="paralax-layer backColor-layer"></div>
          <div data-type='parallax' data-depth="0.50" className="paralax-layer foreground-layer"></div>
          <div data-type='parallax' data-depth="0.50" className="paralax-layer background-layer"></div>
          <div data-type='parallax' data-depth="0.70" className="paralax-layer text-layer">
            <h5>Hi, my name is</h5>
            <h1>Nigel van Duijvendijk</h1>
            <h4>Backend, Frontend, Embedded developer</h4>
          </div>

        </div>
        <div className="background-wrapper">
            <div className="background-blur-purple"></div>
            <div className="background-blur-green"></div>
        </div>
        <main className={styles.main}>
        </main>
      </div>
    </>
  )
}

export default Home
